name: Test Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Python setup
        uses: dataciviclab/.github/actions/python-setup@main
      
      - name: Install dependencies
        run: pip install -e ".[dev]"
      
      - name: Test audit
        uses: dataciviclab/.github/workflows/test-audit-reusable.yml@main
